In [93]:
import numpy as np
import pdb

def Gausu_erase(A,b):
    #Argumented matrix
    Argumented = np.concatenate((A,b),axis=1)
    N = len(A)
    X = np.zeros((1,N)).T
    #progress eliminate
    for k in range(N):
        Argumented[k,:] = Argumented[k,:]/Argumented[k,k]
        for i in range(k+1,N,1):
            Argumented[i,:] = Argumented[i,:] - Argumented[i,k]*Argumented[k,:]
    for n in range(N-1,-1,-1):
        X[n,0] = Argumented[n,N]
        for m in range(n+1,N,1):
            X[n,0] = X[n,0] - Argumented[n,m]*X[m,0] 
    #Recession eliminate
    return X

In [86]:
A = np.array([[-3.0,4.0,5.0],[1.0,0.0,-2.0],[2.0,7.0,-1.0]])
b = np.array([[1.0,-5.0,-6.0]]).T
Gausu_erase(A,b)

> <ipython-input-85-ca0d899e0eaf>(18)Gausu_erase()
-> X[n,0] = X[n,0] - Argumented[n,m]*X[m,0]
(Pdb) c
> <ipython-input-85-ca0d899e0eaf>(17)Gausu_erase()
-> pdb.set_trace()
(Pdb) c
> <ipython-input-85-ca0d899e0eaf>(18)Gausu_erase()
-> X[n,0] = X[n,0] - Argumented[n,m]*X[m,0]
(Pdb) c


array([[ 7.],
       [-2.],
       [ 6.]])

In [91]:
A_Numeric_report = np.array([[1.0,2.0,3.0,4.0],[1.0,4.0,9.0,16.0],[1.0,8.0,27.0,64.0],
                            [1.0,16.0,81.0,256.0]])
b_go = np.array([[0.0,5.0,1.0,0.0]]).T

In [94]:
Gausu_erase(A_Numeric_report,b_go)

array([[-20.16666667],
       [ 21.75      ],
       [-10.5       ],
       [  2.04166667]])

In [97]:
b_sobaji = np.array([[0.0,5.0,5.0,3.0]]).T

In [98]:
Gausu_erase(A_Numeric_report,b_sobaji)

array([[-14.66666667],
       [ 14.5       ],
       [ -6.33333333],
       [  1.16666667]])